version: '3.8'

configs:
  mosquitto.conf:
    file: ./mosquitto/mosquitto.conf
  influxdb.conf:
    file: ./influxdb/influxdb.conf

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
    networks:
      - iot_network

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    configs:
      - source: influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    networks:
      - iot_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - iot_network
    depends_on:
      - influxdb

  adapter:
    image: mhoctavian/adapter:latest
    # This environment variable controls debug logging in Python
    environment:
      - DEBUG_DATA_FLOW=true
    depends_on:
      - mqtt-broker
      - influxdb
    networks:
      - iot_network

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  iot_network:
    driver: overlay