[meta]
  dir = "/var/lib/influxdb2/meta"

[data]
  dir = "/var/lib/influxdb2/data"
  wal-dir = "/var/lib/influxdb2/wal"

[http]
  bind-address = ":8086"
  access-log-enabled = true
  auth-enabled = false  # Setează pe true dacă activezi autentificarea
